### ISSUE TITLE
Question: redhat bug about memory leaks still relevant?

### ISSUE THREAD

**Issue by jubalh** [martinh/libconfuse#121]
I recently found: https://bugzilla.redhat.com/show_bug.cgi?id=1649152
Which is about memory leaks in version 3.2.2. Since this is still the latest stable release I wondered if this is still relevant?

**Comment by troglobit** [comment]
Depends on the client code using libConfuse, does it call `cfg_free()` on the `cfg_t *` from `cfg_init()` or not?

**Comment by jubalh** [comment]
I understood the bugreport more that there is a problem in libconfuse, not that the user uses it wrong.

**Comment by troglobit** [comment]
Not sure I follow, do you want me to prove there are no remaining leaks or assume the user has made no errors?  I'm skeptical because we've had similar reports of leaks before and almost all of them have been due to missing `cfg_free()`. The POC in the bug report is garbled, from what I can see it's not a source file.

Unless you have something else I'm closing this issue.

**Comment by jubalh** [comment]
Nothing else. Thanks for the info.

**Comment by troglobit** [comment]
Thank you for following up.
