### ISSUE TITLE
more compiling error on MSVC(MSVC6/MSVC2010).

### ISSUE THREAD

**Issue by bygreencn** [martinh/libconfuse#16]
1. lexer.c not generated when compile use MSVC.
2. issue for coding.
   --------------------Configuration: libConfuse - Win32 Debug--------------------
   Compiling...
   confuse.c
   e:\github\libconfuse\src\confuse.c(838) : error C2059: syntax error : '.'
   e:\github\libconfuse\src\confuse.c(1123) : error C2065: 'ssize_t' : undeclared identifier
   e:\github\libconfuse\src\confuse.c(1123) : error C2146: syntax error : missing ';' before identifier 'n'
   e:\github\libconfuse\src\confuse.c(1123) : error C2065: 'n' : undeclared identifier
   e:\github\libconfuse\src\confuse.c(1124) : error C2143: syntax error : missing ';' before 'type'
   e:\github\libconfuse\src\confuse.c(1126) : error C2065: 'path' : undeclared identifier
   e:\github\libconfuse\src\confuse.c(1128) : error C2143: syntax error : missing ';' before 'type'
   e:\github\libconfuse\src\confuse.c(1137) : error C2065: 'np' : undeclared identifier
   e:\github\libconfuse\src\confuse.c(1139) : warning C4047: 'return' : 'char *' differs in levels of indirection from 'int '
   e:\github\libconfuse\src\confuse.c(1145) : error C2079: 'st' uses undefined struct 'stat'
   e:\github\libconfuse\src\confuse.c(1325) : warning C4090: 'function' : different 'const' qualifiers
   e:\github\libconfuse\src\confuse.c(1325) : warning C4022: 'free' : pointer mismatch for actual parameter 1
   e:\github\libconfuse\src\confuse.c(1329) : warning C4090: 'function' : different 'const' qualifiers
   e:\github\libconfuse\src\confuse.c(1329) : warning C4022: 'free' : pointer mismatch for actual parameter 1
   Error executing cl.exe.

libConfuse.dll - 9 error(s), 5 warning(s)

**Comment by troglobit** [comment]
We could use some help here guys n gals, neither @martinh or I have access to Windows machines.  

From the looks of it, there could be a few porting issues (`ssize_t`and `confuse.c:838`), the rest (`const` and pointer mismatch issues) looks like stuff I've also seen with a fairly new GCC on Ubuntu 15.10.

**Comment by DavidEGrayson** [comment]
For MSVC, one could use https://appveyor.com

For MSYS2, maybe Alive for would work, or maybe a mingw-64 cross-compiler running in Linux would work.

I am somewhat interested in helping to set up Appveyor so I can learn about it.

**Comment by troglobit** [comment]
Interesting!  I want to set up Travis-CI much in the same way, but since none of this will work via @martinh's account-based project (it's not a GitHub organization), I was thinking that maybe we could delegate responsibilities between us?

Fo my clone of libConfuse I could set up Travis-CI (+ Coverity!), and you could set up Appveyor.  Then when we get it working we could submit pull-requests to the master repo here.  Then continuously fix bugs/integration issues in our own branches and publish them here. 

What do you think?

**Comment by DavidEGrayson** [comment]
My goal would be to set up something that will automatically evaluate every push to master and every pull request in this repository to make sure it can compile in Visual Studio and maybe MSYS2.  Ideally this setup would be entirely handled by GitHub and Appveyor servers.  It should be entirely under your control, and it should not take up my time regularly.

If these goals require the GitHub repository structure to change, so be it.  I'll have to learn more about Appveyor to know that.

I think it will be a nicer experience for everyone to get fast feedback about their pull requests from the build server.

**Comment by DavidEGrayson** [comment]
As a temporary test, I have set up AppVeyor to build from the "vs" branch in my copy the library: https://github.com/DavidEGrayson/libconfuse/tree/vs

It retrieves the repository with git over https, so I could have also pointed it at martinh's copy of the repo.

Now, in order to make it build whenever that branch is updated, I had to go into the Github settings for my repository and add AppVeyor's webhook URL to the repository settings.  @troglobit: are you able to access the Settings page of this repository, and add webhook URLs?

**Comment by troglobit** [comment]
Yep, I'd also very much like for it to be handled centrally from the main repository.  This potentially requires setting up a libConfuse organization in GitHub.   At the moment only @martinh can access the settings page of the repo, I've only got push-access (and possibly the Wiki).

On a similar not I set up Travis-CI earlier today https://travis-ci.org/troglobit/libconfuse/builds from my own libConfuse fork, along with a Coverity Scan setup https://scan.coverity.com/projects/troglobit-libconfuse ... anyone who wants I can give them read-access to inspect the Coverity issues. 

For the time being we'll have to make due with this, I think.  But I'll put together a proposal with several items for @martinh later on, so we don't bombard him with requests eating up the little time he can spare.

**Comment by DavidEGrayson** [comment]
Without bugging martinh, I believe that you, I, or anyone interested could at least set up an Appveyor project that points to martinh/libconfuse.  They could manually start builds using the Appveyor web interface whenever they want to make sure that martinh/libconfuse builds correctly in Visual Studio.  This would make it possible to test with Visual Studio before each release, or whenever you feel like it.

If they want the Appveyor project to automatically build, we need to install that web hook in the Github settings.

Cool that you got travis-ci working.

**Comment by DavidEGrayson** [comment]
I am working on the Visual Studio support on this branch, which will eventually be a pull request: https://github.com/DavidEGrayson/libconfuse/tree/vs2

My current sticking point is that the Visual Studio project refers to `..\..\..\src\lexer.c`, which doesn't exist.  I guess I'll write a bash script that you can run in a nice environment like MSYS2 to generate lexer.c and copy it to somewhere in the "windows" directory.

**Comment by troglobit** [comment]
Ah, I can imagine there are a few problems with this "out of tree" stuff. Is there no way of just adding another search path to VS?  I have no problem with another script though, we already have separate distribution of windows (zip) and unix (tarball) files.

**Comment by DavidEGrayson** [comment]
Visual Studio can use any source or header file in the repository.  The problem is that `lexer.c` is generated from `lexer.l` at build time by flex, and I assume that flex isn't available in Visual Studio, so someone needs to generate lexer.c at some point for the Visual Studio users.

Alternatively, we could decide we don't care about Visual Studio and tell people who complain to use MSYS2 instead.  :-)

**Comment by DavidEGrayson** [comment]
OK, I can see now that lexer.c actually gets generated somehow and included in the .xz archives and the .zip archives that are released [here](https://github.com/martinh/libconfuse/releases).  So that should cover regular users Visual Studio users who want to use the library.  So it is actually something that happens before build time.

But how should a continuous integration server like Appveyor get its copy of lexer.c?  I'm not sure what the best solution is.  If we add lexer.c to the repository, we have to remember to keep it updated.

**Comment by troglobit** [comment]
I'm usually against keeping generated files in the repo ... is there no other way around this?

For Travis-CI I have to install autopoint, or autogen.sh fails. Is is possible to add a pass before the actual build that installs and runs flex?

(I think it might just have been an unintended side effect that lexer.c is distributed at the moment.)

**Comment by DavidEGrayson** [comment]
I now know that AppVeyor has MSYS2 installed by default, so it would be possible to generate lexer.c using MSYS2 before invoking MsBuild.

**Comment by troglobit** [comment]
Good, if we can avoid generated files in the repo I'm a happy camper.

No, `autogen.sh` does not create `lexer.c`.  You must run the configure script followed by `make -C src lexer.c`

**Comment by peda-r** [comment]
See pull #36 for patches for MSVC 2010...

**Comment by troglobit** [comment]
Closing, very old issue and likely fixed in #36.  Please open a new issue in the tracker for further reports.
