### ISSUE TITLE
Feature request: ignore unknown options

### ISSUE THREAD

**Issue by jimgeorge** [martinh/libconfuse#19]
It would be nice to have a flag to ignore any options or sections that are not specified in the cfg_opt_t array passed to cfg_init. Currently, if there is some option in the config file that is not specified, a parse error is returned by cfg_parse.

**Comment by fhunleth** [comment]
+1. I'd be interested in this feature as well.

**Comment by fhunleth** [comment]
@jimgeorge - I submitted a start at this feature. See pull request #20. Adding this universally looks difficult due to type information (string vs. list, etc) being used to guide the parsing of the config files. In my use case, ignoring unknown options is more of an issue than unknown sections, so pr #20 helps me. Maybe it will help you.

**Comment by troglobit** [comment]
Related to #24, would be great to have support for handling unknown sections as well ...

**Comment by troglobit** [comment]
Closing this for now, support for ignoring options has been added in PR #46.  If we need support for ignoring sections as well, we should file another issue.
