### ISSUE TITLE
Are nested sections supported?

### ISSUE THREAD

**Issue by ThomasAdam** [martinh/libconfuse#42]
Hello!

I'm trying to use nested sections in libconfuse, is tihs supported?  Here's the configuration I'd *like* to use:

```
groups {
	name = 'Esmé'
	group 1 {
		number = 1
	}
}
```

Here's the C program I've written to represent that:

```
#include <confuse.h>
#include <stdio.h>
#include <string.h>

int main(void)
{
	cfg_opt_t opts[] = {
		CFG_SEC("group", CFGF_NONE, CFGF_TITLE | CFGF_MULTI),
		CFG_INT("number", 0, CFGF_NONE),
		CFG_END()
	};

	cfg_opt_t groups_opts[] = {
		CFG_SEC("groups", opts, CFGF_NONE),
		CFG_STR("name", "Esmé", CFGF_NONE),
		CFG_END()
	};

	cfg_t *cfg;

	cfg = cfg_init(groups_opts, CFGF_NONE);
	if (cfg_parse(cfg, "example.conf") == CFG_PARSE_ERROR)
		return 1;

	cfg_free(cfg);
	return 0;
}
```
When compiling the program above, and running it *without* a configuration file, my test program segfaults.  *With* a configuration file, it complains about "name" being an unknown option.

Am I being a numpty, or is this not supported?

TIA!

**Comment by troglobit** [comment]
Hi Thomas,

It's definitely possible!  You just went about it a little bit backwards :smiley:
I took the liberty of making a pull request of your example, slightly fixed #43:

https://github.com/troglobit/libconfuse/commit/85c3f3c

I hope this helps and is what you asked for!

**Comment by ThomasAdam** [comment]
Thanks, @troglobit -- I know see how I was going about this the wrong way.  Whoops!  I think what I might do as well when I get some time is augment the libconfuse tutorial with such an example, and/or expand other sections.  Is the tutorial something which is maintained still, and would such tweaks be welcomed?

**Comment by troglobit** [comment]
Good to hear that helped, no problem! :smiley: 

Any form of update is welcome, but updates to documentation in particular are *very* welcome! Just post a pull-request and I'll merge it after audit.

Only problem atm. is that we cannot update the homepage anymore since the original author has basically gone AWOL.  The idea is to generate GitHub wiki content from the sources instead.  If that fails I may host the docs on http://troglobit.com ...

Anyway, I'll be closing this issue then.
